stages:
  - install
  - build_cloudformation
  - execute_init_cloudformation
  - execute_cloudformation

install_dependencies:
  image: node:20-alpine
  stage: install
  script:
    - cd Lambdas/src
    - >
      find . -type d | while read dir; do
        if [ -f "$dir/package.json" ]; then
          echo "Found package.json in $dir. Running npm install..."
          cd "$dir" && npm install && cd -
        else
          echo "No package.json found in $dir. Skipping npm install."
        fi
      done
  only:
    - test-ci
  artifacts:
    paths:
      - Lambdas/src/**

build_cloudformation:
  image: node:20-alpine
  stage: build_cloudformation
  script:
    - cd Lambdas
    - mkdir output
    - cd ../infrastructure
    - npm install
    - node generate_apigateway_cloudbuild.js
  only:
    - test-ci
  artifacts:
    paths:
      - infrastructure/output.yaml
      - Lambdas/src/**
      - Lambdas/output/**

execute_init_cloudformation:
  image: amazon/aws-cli
  stage: execute_init_cloudformation
  script:
    - aws cloudformation deploy --template-file ".infrastructure/init.yaml" --stack-name PreDeployStack