stages:
  - install
  - build_cloudformation
  - execute_init_cloudformation
  - execute_cloudformation

install_dependencies:
  image: node:20-alpine
  stage: install
  script:
    - cd Lambdas/src
    - >
      find . -type d | while read dir; do
        if [ -f "$dir/package.json" ]; then
          echo "Found package.json in $dir. Running npm install..."
          cd "$dir" && npm install && cd -
        else
          echo "No package.json found in $dir. Skipping npm install."
        fi
      done
  only:
    - test-ci
  artifacts:
    paths:
      - Lambdas/src/**

build_cloudformation:
  image: node:20-alpine
  stage: build_cloudformation
  script:
    - cd Lambdas
    - mkdir output
    - cd ../infrastructure
    - npm install
    - node generate_apigateway_cloudbuild.js
  only:
    - test-ci
  artifacts:
    paths:
      - infrastructure/output.yaml
      - Lambdas/src/**
      - Lambdas/output/**

execute_init_cloudformation:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  stage: execute_init_cloudformation
  script:
    - rm -rf ~/.aws/credentials
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region $AWS_DEFAULT_REGION
    - aws --version
    - aws cloudformation deploy --template-file ./infrastructure/init.yaml --stack-name PreDeployStack