stages:
  - install
  - build_cloudformation

install_dependencies:
  image: node:20-alpine
  stage: install
  script:
    - cd Lambdas/src
    - >
      find . -type d | while read dir; do
        if [ -f "$dir/package.json" ]; then
          echo "Found package.json in $dir. Running npm install..."
          cd "$dir" && npm install && cd -
        else
          echo "No package.json found in $dir. Skipping npm install."
        fi
      done
  only:
    - test-ci
  artifacts:
    paths:
      - Lambdas/src/**

build_cloudformation:
  image: node:20-alpine
  stage: build_cloudformation
  script:
    - cd Lambdas
    - mkdir output
    - cd ../infrastructure
    - node generate_api_gateway.js
  only:
    - test-ci
  artifacts:
    paths:
      - output.yaml
      - Lambdas/src/**