stages:
  - install
  - build_cloudformation
  - execute_cloudformation
  - deploy_lambda_code

install_dependencies:
  # when: manual
  image: node:20-alpine
  stage: install
  script:
    - cd Lambdas/src
    - >
      find . -type d | while read dir; do
        if [ -f "$dir/package.json" ]; then
          echo "Found package.json in $dir. Running npm install..."
          cd "$dir" && npm install && cd -
        else
          echo "No package.json found in $dir. Skipping npm install."
        fi
      done
    - cd ../extra_lambdas/node
    - >
      find . -type d | while read dir; do
        if [ -f "$dir/package.json" ]; then
          echo "Found package.json in $dir. Running npm install..."
          cd "$dir" && npm install && cd -
        else
          echo "No package.json found in $dir. Skipping npm install."
        fi
      done
  artifacts:
    paths:
      - Lambdas/src/**
      - Lambdas/extra_lambdas/**
  only:
    - main

build_cloudformation:
  # when: manual
  image: node:20-alpine
  stage: build_cloudformation
  script:
    - cd Lambdas
    - mkdir output
    - cd ../infrastructure
    - npm install
    - node generate_apigateway_cloudbuild.js
  artifacts:
    paths:
      - infrastructure/output.yaml
      - Lambdas/output/**
  only:
    - main

execute_cloudformation:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  stage: execute_cloudformation
  before_script:
    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
    - export NVM_DIR="$HOME/.nvm"
    - \[ -s "$NVM_DIR/nvm.sh" \] && \. "$NVM_DIR/nvm.sh"
    - nvm install 20
    - npm install -g @cumulusds/aws-cloudformation-wait-ready
  script:
    - aws cloudformation deploy --template-file ./infrastructure/PreDeployStack.yaml --stack-name PreDeployStack --capabilities CAPABILITY_NAMED_IAM;
    - aws-cloudformation-wait-ready --region us-east-1 --stack-name PreDeployStack
    - aws s3 cp Lambdas/output/ s3://csci-5410-s24-sdp-5-lambda-code/ --recursive
   # Check if ApiDeploymentStack exists
    - aws cloudformation deploy --template-file ./infrastructure/output.yaml --stack-name ApiDeploymentStack --capabilities CAPABILITY_NAMED_IAM;
    - aws-cloudformation-wait-ready --region us-east-1 --stack-name ApiDeploymentStack

    - aws cloudformation deploy --template-file ./infrastructure/PostDeployStack.yaml --stack-name PostDeployStack --capabilities CAPABILITY_NAMED_IAM;
    - aws-cloudformation-wait-ready --region us-east-1 --stack-name PostDeployStack
  only:
    - main

deploy_lambda_code:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  stage: deploy_lambda_code
  script:
    - sh ./infrastructure/deploy-lambda.sh
  only:
    - main