AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Initial Infrastructure

Resources:
  LambdaCodeBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 'csci-5410-s24-sdp-5-lambda-code'
      
  DalVacationBookingQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: DalVacationBooking

  BookingsTableQueue:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: BookingsTable
      AttributeDefinitions:
        - AttributeName: bookingId
          AttributeType: S
      KeySchema:
        - AttributeName: bookingId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1