AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Initial Infrastructure

Resources:
  DalVacationBookingQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: DalVacationBooking
      VisibilityTimeout: 60

  DalVacationBookingLambdaEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 1
      EventSourceArn: !GetAtt DalVacationBookingQueue.Arn
      FunctionName: arn:aws:lambda:us-east-1:845434235447:function:BookingNotificationIac
      Enabled: True

  DalVacationPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: DalVacationPool
      AliasAttributes: 
        - preferred_username
      AutoVerifiedAttributes: 
        - email
      MfaConfiguration: "OFF"
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: "verified_email"
            Priority: 1
      Schema:
        - Name: "role"
          AttributeDataType: "String"
          Mutable: True
        - Name: "sns_topic_arn"
          AttributeDataType: "String"
          Mutable: True
      LambdaConfig:
        CreateAuthChallenge: arn:aws:lambda:us-east-1:845434235447:function:CreateAuthChallengeIac
        DefineAuthChallenge: arn:aws:lambda:us-east-1:845434235447:function:DefineAuthChallengeIac
        PostAuthentication: arn:aws:lambda:us-east-1:845434235447:function:PostAuthTriggerIac
        PostConfirmation: arn:aws:lambda:us-east-1:845434235447:function:PostConfTriggerIac
        PreSignUp: arn:aws:lambda:us-east-1:845434235447:function:PreSignUpTriggerIac
        VerifyAuthChallengeResponse: arn:aws:lambda:us-east-1:845434235447:function:VerifyAuthChallengeIac
      EmailConfiguration:
        EmailSendingAccount: "COGNITO_DEFAULT"

  DalVacationPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: DalVacationPoolClient
      UserPoolId: !Ref DalVacationPool
      ExplicitAuthFlows:
        - "ALLOW_CUSTOM_AUTH"
        - "ALLOW_USER_SRP_AUTH"
        - "ALLOW_REFRESH_TOKEN_AUTH"